// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCmX4-sQeTYEajPqCy3V2KfS4mn9jPr76Q',
    appId: '1:1015752668490:web:2b52eef903a43cd292bdb3',
    messagingSenderId: '1015752668490',
    projectId: 'omnicardai',
    authDomain: 'omnicardai.firebaseapp.com',
    storageBucket: 'omnicardai.firebasestorage.app',
    measurementId: 'G-7KEXYB1KFL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAl3Ucrw_sKoo4HqseDWx9swd5EcwIn4-k',
    appId: '1:1015752668490:android:da60adbd50ccb0f692bdb3',
    messagingSenderId: '1015752668490',
    projectId: 'omnicardai',
    storageBucket: 'omnicardai.firebasestorage.app',
  );
}
